url: https://hge-ci-pull-5629.herokuapp.com/v1/graphql
headers:
  X-Hasura-Admin-Secret: my-secret
queries:
  - name: users
    tools: [ autocannon,k6, wrk2]
    execution_strategy: REQUESTS_PER_SECOND
    rps: 500
    duration: 5s
    query: |
      mutation MyMutation {
        insert_user_one(object: {name: "test"}) {
          id
        }
      }
    